[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
SoapyLMS7_jll = "e7ed14a0-13eb-5dc7-93e2-6133b2eb8bed"
SoapyLoopback_jll = "8d250ce8-a086-56bd-8a36-e4e8f4202680"
SoapySDR = "4fa426e6-03fd-45b2-b2dd-25f726820c03"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
soapysdr_jll = "343a40d9-ed99-5d34-8b56-649aaa4ecee6"
